name: Build Android APK & Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Autorise la création de la Release GitHub

jobs:
  build:
    name: Build & Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # On anticipe la fin de Node 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Prebuild Android project
        run: npx expo prebuild -p android --clean

      - name: Decode Keystore
        run: |
          # On décode la clé stockée dans les secrets GitHub pour la rendre utilisable par Gradle
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/wastemap.jks
        continue-on-error: false

      - name: Assemble Release APK
        run: |
          cd android
          chmod +x gradlew
          # Compilation avec signature dynamique via les secrets
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=${{ github.workspace }}/android/app/wastemap.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }} \
            --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wastemap-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 7

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: android/app/build/outputs/apk/release/app-release.apk
          name: Release ${{ github.ref_name }}
          body: |
            Build automatique de Wastemap.
            Version : ${{ github.ref_name }}
            Date : ${{ github.event.head_commit.timestamp }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}